SELECT 
    SUB.AUTHOR_ID, A.AUTHOR_NAME, SUB.CATEGORY,
    SUM(SUB.SUM_SALES) AS TOTAL_SALES
FROM 
(
    SELECT 
        B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, 
        (SUM(SALES) * B.PRICE) AS SUM_SALES
    FROM BOOK B
    JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY 
        B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID
    ORDER BY B.BOOK_ID
) SUB
JOIN AUTHOR A ON SUB.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, SUB.CATEGORY
ORDER BY A.AUTHOR_ID, SUB.CATEGORY DESC