-- 코드를 입력하세요
SELECT SUB.CART_ID
FROM
    (
    SELECT CART_ID, 
        COUNT(CASE WHEN NAME='Yogurt' THEN NAME END) AS YCOUNT, 
        COUNT(CASE WHEN NAME='Milk' THEN NAME END) AS MCOUNT
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk', 'Yogurt')
    GROUP BY CART_ID
    ) SUB
WHERE YCOUNT > 0 AND MCOUNT > 0
ORDER BY CART_ID