SELECT 
    H.HISTORY_ID, 
    FLOOR(C.DAILY_FEE * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100) * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
LEFT JOIN (
    SELECT DP.CAR_TYPE, DP.DISCOUNT_RATE, 
           CAST(REGEXP_REPLACE(DP.DURATION_TYPE, '[^0-9]+', '') AS UNSIGNED) AS DURATION_DAYS
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
) D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_DAYS = (
        SELECT MAX(CAST(REGEXP_REPLACE(DP2.DURATION_TYPE, '[^0-9]+', '') AS UNSIGNED))
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP2
        WHERE DP2.CAR_TYPE = D.CAR_TYPE
        AND CAST(REGEXP_REPLACE(DP2.DURATION_TYPE, '[^0-9]+', '') AS UNSIGNED) <= DATEDIFF(H.END_DATE, H.START_DATE) + 1
    )
WHERE C.CAR_TYPE = '트럭'  -- 🚨 "트럭"만 조회하는 필터 추가
ORDER BY FEE DESC, H.HISTORY_ID DESC;
