-- 코드를 입력하세요
SELECT SUB.FLAVOR
FROM 
(
    SELECT
        J.FLAVOR,
        IFNULL(J.JULY_TOTAL_ORDER, 0) + IFNULL(F.TOTAL_ORDER, 0) AS TOTAL_ORDER
    FROM 
    (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
        FROM JULY 
        GROUP BY FLAVOR
    ) J
    LEFT JOIN FIRST_HALF F ON F.FLAVOR = J.FLAVOR
) SUB
ORDER BY TOTAL_ORDER DESC
LIMIT 3